# These are supported funding model platforms

github: edent # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: edent # Replace with a single Patreon username
open_collective: edent # Replace with a single Open Collective username
ko_fi: edent # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom: https://www.amazon.co.uk/gp/registry/ref=as_li_ss_tl?ie=UTF8&id=13GFCFR2B2IX4&type=wishlist&linkCode=ll2&tag=edentgithub-21&linkId=72adccc3a979d061f927aefe823fc39a&language=en_GB # Replace with a single custom sponsorship URL
